name: Windows Release Build

on:
  workflow_dispatch:

jobs:
  win-release:
    name: Windows CLI Release
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DINPUTLEAP_BUILD_GUI=OFF `
            -DINPUTLEAP_BUILD_TESTS=OFF `
            -DINPUTLEAP_VERSION_DESC=release `
            -DCMAKE_INSTALL_PREFIX=install

      - name: Build
        run: cmake --build build --config Release --target install

      - name: Package
        run: |
          Compress-Archive -Path "install\*" -DestinationPath input-leap-win-release.zip

      - uses: actions/upload-artifact@v4
        with:
          name: input-leap-win-release
          path: input-leap-win-release.zip
          if-no-files-found: error
