name: Windows Release Build

on:
  workflow_dispatch:

env:
  B_BUILD_TYPE: Release

jobs:
  win-release:
    name: Windows Release (Qt6)
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Bonjour SDK-like
        id: bonjour
        run: |
          $ErrorActionPreference = "Stop"
          New-Item -Force -ItemType Directory -Path .\deps
          Invoke-WebRequest 'https://github.com/nelsonjchen/mDNSResponder/releases/download/v2019.05.08.1/x64_RelWithDebInfo.zip' -OutFile 'deps\BonjourSDKLike.zip'
          Expand-Archive .\deps\BonjourSDKLike.zip -DestinationPath .\deps\BonjourSDKLike
          Remove-Item deps\BonjourSDKLike.zip
          "path=$env:GITHUB_WORKSPACE\deps\BonjourSDKLike" >> $env:GITHUB_OUTPUT

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6
          cache: true
          cache-key-prefix: windows-2022-Qt6.6

      - name: Configure
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DQT_DEFAULT_MAJOR_VERSION=6 `
            -DINPUTLEAP_VERSION_DESC=release `
            -DINPUTLEAP_BUILD_TESTS=OFF `
            -DDNSSD_LIB="${{ steps.bonjour.outputs.path }}\Lib\x64\dnssd.lib" `
            -DCMAKE_INSTALL_PREFIX=install
        env:
          BONJOUR_SDK_HOME: ${{ steps.bonjour.outputs.path }}

      - name: Build
        run: cmake --build build --config Release --target install
        env:
          BONJOUR_SDK_HOME: ${{ steps.bonjour.outputs.path }}

      - name: Deploy Qt DLLs
        run: |
          windeployqt --release --no-translations --no-opengl-sw install\input-leap.exe

      - name: Package
        run: Compress-Archive -Path "install\*" -DestinationPath input-leap-win-release.zip

      - uses: actions/upload-artifact@v4
        with:
          name: input-leap-win-release
          path: input-leap-win-release.zip
          if-no-files-found: error
